Update git pipeline

diff --git a/.github/workflows/dev.yaml b/.github/workflows/dev.yaml
--- a/.github/workflows/dev.yaml
+++ b/.github/workflows/dev.yaml
@@ -23,38 +23,34 @@ jobs:
         status: STARTED
         color: warning
 
-    - name: Set version
-      id: vars
-      run: echo "::set-output name=version::$(echo ${GITHUB_SHA} | cut -c1-7)"
-
-    - name: Configure AWS credentials
-      uses: aws-actions/configure-aws-credentials@v1
+    - name: Setup Nodejs
+      uses: actions/setup-node@v1
       with:
-        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
-        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
-        aws-region: us-east-2
+        node-version: '16.x'
 
-    - name: Login to Amazon ECR
-      id: login-ecr
-      uses: aws-actions/amazon-ecr-login@v1
+    - name: Cache dependencies
+      id: node-cache
+      uses: actions/cache@v2
+      with:
+        path: |
+          **/node_modules
+        key: dev-${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}
 
-    - name: Build, tag and push the image
+    - name: Install dependencies
+      if: steps.node-cache.output.cache-hit != 'true'
+      run: yarn install --pure-lockfile
+
+    - name: Build
+      run: yarn build
       env:
-        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
-        ECR_REPOSITORY: filecoin/filgreen/filecoin-green-webapp
-        IMAGE_TAG: ${{ steps.vars.outputs.version }}
-      run: |
-        docker build \
-          --build-arg REACT_APP_API_BASE_URL=https://api.filgreen.d.interplanetary.one/  \
-          -t ${ECR_REGISTRY}/${ECR_REPOSITORY}:dev-${IMAGE_TAG}    \
-          ${GITHUB_WORKSPACE}
-        docker push $ECR_REGISTRY/$ECR_REPOSITORY:dev-${IMAGE_TAG}
+        CI: false
+        REACT_APP_API_BASE_URL: https://api.filgreen.d.interplanetary.one/
 
-    - name: Echo IMAGE_TAG
-      env:
-        IMAGE_TAG: ${{ steps.vars.outputs.version }}
-      run: |
-        echo "Version to set in deployment manifests: dev-${IMAGE_TAG}"
+    - name: Save artifacts
+      uses: actions/upload-artifact@v2
+      with:
+        name: dev-frontend
+        path: build
 
     - name: Notify Slack success
       if: success()
@@ -78,7 +74,66 @@ jobs:
         status: FAILED
         color: danger
 
-    - name: Logout from Amazon ECR
-      if: always()
-      run: |
-        docker logout ${{ steps.login-ecr.outputs.registry }}
+  deploy:
+    needs: build
+    runs-on: ubuntu-latest
+    steps:
+      - name: Notify Slack
+        if: success()
+        id: slack
+        env:
+          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
+        uses: voxmedia/github-action-slack-notify-build@v1
+        with:
+          channel: infra-ci-filgreen
+          status: DEPLOYMENT STARTED
+          color: warning
+
+      - name: Get artifacts
+        uses: actions/download-artifact@v2
+        with:
+          name: dev-frontend
+
+      - name: Configure AWS credetials
+        uses: aws-actions/configure-aws-credentials@v1
+        with:
+          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
+          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
+          aws-region: us-east-2
+
+      - name: Deploy static site to S3
+        run: ls -l && aws s3 sync . s3://dev-filgreendinterplanetaryone-origin --delete
+
+      - name: Invalidate CloudFront cache
+        run: |
+          #!/usr/bin/env bash
+          set -eou pipefail
+          CF_DIST_ID=$(aws cloudfront list-distributions --query "DistributionList.Items[?Aliases.Items!=null] | [?contains(Aliases.Items, 'filgreen.d.interplanetary.one')].Id | [0]" | tr -d \")
+          echo "Clearing cache for ${CF_DIST_ID}..."
+          CF_INVALIDATION_ID=$(aws cloudfront create-invalidation --distribution-id ${CF_DIST_ID} --paths "/*" | jq -r '.Invalidation.Id')
+          while [ $(aws cloudfront get-invalidation --distribution-id ${CF_DIST_ID} --id ${CF_INVALIDATION_ID} | jq -r '.Invalidation.Status') != "Completed" ]; do
+            echo "CF_DIST_ID=${CF_DIST_ID} CF_INVALIDATION_ID=${CF_INVALIDATION_ID}: Waiting for CloudFront cache invalidation to complete..."
+            sleep 5
+          done
+
+      - name: Notify Slack
+        if: success()
+        env:
+          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
+        uses: voxmedia/github-action-slack-notify-build@v1
+        with:
+          channel: infra-ci-filgreen
+          message_id: ${{ steps.slack.output.message_id }}
+          status: DEPLOYMENT SUCCESSFUL
+          color: good
+
+      - name: Notify Slack
+        if: failure()
+        env:
+          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
+        uses: voxmedia/github-action-slack-notify-build@v1
+        with:
+          channel: infra-ci-filgreen
+          message_id: ${{ steps.slack.output.message_id }}
+          status: DEPLOYMENT FAILED
+          color: danger
